### ISSUE TITLE
How to solve it

### ISSUE THREAD

**Issue by lolisa** [lolisa/what-to-do-next#11]

**Comment by Heather** [comment]
I don't know

**Comment by lolisa** [comment]
@Heather It is the name of a book... BTW work piles up so quickly :)

**Comment by Heather** [comment]
@lolisa hm..... this one http://www.amazon.com/How-Solve-It-Mathematical-Princeton/dp/069111966X ? Suggested by someone?

**Comment by lolisa** [comment]
Yep.
