### ISSUE TITLE
Linear Algebra

### ISSUE THREAD

**Issue by lolisa** [lolisa/what-to-do-next#2]

**Comment by eccstartup** [comment]
Linear Algebra -> Abstract Algebra
SICP
Topology -> hott

**Comment by lolisa** [comment]
噗，看我什么不好竟然看我这个，如果不是我不想花钱我绝对做成private
另外SICP AbstractAlgebra我本来就打算读
Hott则是以前读过，看不懂放弃了所以才打算Topology补基础

**Comment by eccstartup** [comment]
我也是不故意看到的，学点数学基础很好啊。数学基础一般就是：分析，代数，拓扑。

**Comment by lolisa** [comment]
没啥，只是自嘲一下辛辛苦苦写的代码没人看随手写的note已经有两个人了。。。

**Comment by lolisa** [comment]
https://github.com/lolisa/linear_algebra
